# index:
#    path: /
#    controller: App\Controller\HomeController::index
index:
   path: /
   controller: App\Controller\HomeController::index


login:
   path: /login
   controller: App\Controller\LoginController::index


menu:
   path: /menu
   controller: App\Controller\MenuController::index




admin:
   path: /admin
   controller: App\Controller\AdminController::index

upload:
   path: /upload
   controller: App\Controller\UploadController::index



addImage:
   path: /add_image
   controller: App\Controller\AddImageController::index


add_dossier:
   path: /add_dossier/{catego}
   controller: App\Controller\ManagerController::addDossier


manager:
   path: /manager
   controller: App\Controller\ManagerController::index

portfolio:
   path: /portfolio
   controller: App\Controller\AdminController::portfolio


categorie:
   path: /categorie
   controller: App\Controller\CategorieController::index
   
add_categorie:
   path: /add_categorie
   controller: App\Controller\CategorieController::add

categorie-pool:
   path: /photo/{categorie}
   controller: App\Controller\PhotoController::categorie


dossier:
   path: /photo/{categorie}/{dossier}
   controller: App\Controller\PhotoController::dossier

photo:
   path: /photo
   controller: App\Controller\PhotoController::index